apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice-sandbox
bases:
- ../../common
resources:
- secret.yaml
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
commonAnnotations:
  owner: gozer@mozilla.com
  team: itsre
  costcenter: "1440"
